# -*- coding: utf-8 -*-
from fastapi import FastAPI
from sqlalchemy import create_engine
import pandas as pd
import uuid
from pydantic import BaseModel

app = FastAPI()
cache_dict = {}

class DataItem(BaseModel):
    data_id: str

class DatabaseItem(BaseModel):
    engine_url: str

class ReadDataItem(BaseModel):
    sql: str
    engine_url: str

class AnalyzeItem(BaseModel):
    data_id: str
    code: str

class GetTableStructureItem(BaseModel):
    table_name: str
    engine_url: str

def run_code(dataFrame, code: str):
    context = {'dataFrame': dataFrame}
    exec(code, {}, context)
    return context.get('result')

@app.get("/")
async def index():
    return {"message": "Welcome to AutoReport!"}

@app.post("/list_tables")
async def list_tables(item: DatabaseItem):
    try:
        if item.engine_url == "":
            return {"status": False, "error": "`engine_url` cannot be empty!"}
        engine = create_engine(item.engine_url)
        if engine.name == "mysql":
            sql = "SELECT TABLE_NAME AS table_name,TABLE_COMMENT AS table_comment FROM information_schema.TABLES WHERE TABLE_SCHEMA = '%s';" % engine.url.database
        elif engine.name == "postgresql":
            sql = "SELECT t.relname AS table_name,obj_description(t.oid, 'pg_class') AS table_comment FROM pg_class t JOIN pg_namespace n ON t.relnamespace = n.oid WHERE t.relkind = 'r' AND n.nspname NOT IN ('information_schema', 'pg_catalog') AND n.nspname = 'public';"
        else:
            return {"status": False, "error": "database type not support!"}

        df = pd.read_sql(sql, engine)
        return {"status": True, "data": df.to_csv()}
    except Exception as err:
        return {"status": False, "error": err}

@app.post("/get_table_structure")
async def get_table_structure(item: GetTableStructureItem):
    try:
        if item.engine_url == "" or item.table_name == "":
            return {"status": False, "error": "`engine_url` or `table_name` cannot be empty!"}
        engine = create_engine(item.engine_url)
        if engine.name == "mysql":
            sql = """SELECT
                    COLUMN_NAME        AS `名称`,
                    COLUMN_TYPE        AS `类型`,
                    IS_NULLABLE        AS `是否允许为空`,
                    COLUMN_DEFAULT     AS `默认值`,
                    COLUMN_KEY         AS `键类型`,
                    EXTRA              AS `额外属性`,
                    COLUMN_COMMENT     AS `字段注释`
                FROM
                    information_schema.COLUMNS
                WHERE
                    TABLE_SCHEMA = '%s'
                    AND TABLE_NAME = '%s'
                ORDER BY
                    ORDINAL_POSITION;
            """ % (engine.url.database, item.table_name)
        elif engine.name == "postgresql":
            sql = """SELECT
                    a.attname AS column_name,
                    pg_catalog.format_type(a.atttypid, a.atttypmod) AS data_type,
                    CASE WHEN a.attnotnull THEN 'NO' ELSE 'YES' END AS is_nullable,
                    pg_get_expr(d.adbin, d.adrelid) AS column_default,
                    COALESCE(
                        (SELECT pg_get_constraintdef(oid) 
                        FROM pg_constraint 
                        WHERE conrelid = a.attrelid 
                        AND contype = 'p' 
                        AND a.attnum = ANY(conkey)), 
                        ''
                    ) AS primary_key,
                    COALESCE(
                        (SELECT string_agg(pg_get_constraintdef(oid), '; ') 
                        FROM pg_constraint 
                        WHERE conrelid = a.attrelid 
                        AND contype = 'u' 
                        AND a.attnum = ANY(conkey)), 
                        ''
                    ) AS unique_constraint,
                    CASE 
                        WHEN a.attidentity = 'a' THEN 'generated always as identity'
                        WHEN a.attidentity = 'd' THEN 'generated by default as identity'
                        WHEN a.attgenerated != '' THEN 'generated'
                        ELSE ''
                    END AS extra,
                    col_description(a.attrelid, a.attnum) AS column_comment
                FROM
                    pg_catalog.pg_attribute a
                LEFT JOIN
                    pg_catalog.pg_attrdef d ON a.attrelid = d.adrelid AND a.attnum = d.adnum
                WHERE
                    a.attrelid = '%s'::regclass
                    AND a.attnum > 0
                    AND NOT a.attisdropped
                ORDER BY
                    a.attnum;
            """ % item.table_name
        else:
            return {"status": False, "error": "database type not support!"}

        df = pd.read_sql(sql, engine)
        return {"status": True, "data": df.to_csv()}
    except Exception as err:
        return {"status": False, "error": err}

@app.post("/cache_data")
async def read_data(item: ReadDataItem):
    try:
        if item.engine_url == "" or item.sql == "":
            return {"status": False, "error": "`engine_url` or `sql` cannot be empty!"}
        
        # query data
        engine = create_engine(item.engine_url)
        df = pd.read_sql(item.sql, engine)
        row_count = df.shape[1]
        memory_usage = df.memory_usage().sum()

        # cache data
        random_uuid = uuid.uuid4()
        cache_dict[random_uuid] = df

        result = {"status": True, "data_id": random_uuid, "row_count": row_count}
        if memory_usage < 1024:
            result["data"] = df.to_json(force_ascii=False)

        return result
    except Exception as err:
        return {"status": False, "error": err}


@app.post("/delete_data")
async def delete_data(item: DataItem):
    if item.data_id in cache_dict:
        cache_dict.pop(item.data_id)
    return {"status": True}

@app.post("/analyze")
async def analyze(item: AnalyzeItem):
    try:
        if item.data_id == "" or item.code == "":
            return {"status": False, "error": "`data_id` or `code` cannot be empty!"}
        if item.data_id in cache_dict:
            result = run_code(cache_dict[item.data_id], item.code)
            return {"status": True, "result": result}
        else:
            return {"status": False, "error": "cache data id `%s` not found!" % item.data_id}
    except Exception as err:
        return {"status": False, "error": err}

if __name__ == '__main__':
    pass
